[package]
name = "aprireader"
version = "1.1.0"
description = "ApriReader desktop application"
authors = ["Bahadur"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Aprilarius/ApriReader"
homepage = "https://github.com/Aprilarius/ApriReader"

[features]
default = []
steam-build = []

[lib]
name = "aprireader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
quick-xml = { version = "0.41", features = ["encoding"] }
rars = "0.4.7"
rusqlite = { version = "0.37", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-opener = "2.5.4"
thiserror = "2"
ureq = { version = "3.3.0", default-features = false, features = ["json", "rustls"] }
zip = { version = "8.6", default-features = false, features = ["deflate"] }

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2.3.6"

[dev-dependencies]
tempfile = "3"

[profile.steam-release]
inherits = "release"
lto = "thin"
