allowBuilds:
  esbuild: true
onlyBuiltDependencies:
  - esbuild
overrides:
  minimatch@3>brace-expansion: "^1.1.18"
  minimatch@9>brace-expansion: "^2.1.4"
  js-yaml@>=4.0.0 <4.3.1: ">=4.3.1 <5.0.0"
  nanoid@<3.3.18: "^3.3.18"
